name: 'Add Activity'
description: 'Add activity to Orbit workspace'
inputs:
  workspace:  # id of input
    description: 'Workspace to add activity to'
    required: true
  api_key:
    description: 'API key for Orbit'
    required: true
outputs:
  activity: # id of output
    description: 'Activity response'
runs:
  using: 'node16'
  main: 'index.js'